name: Linter
on: [pull_request]

jobs:
  spell-check:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.2
        with:
          ref: ${{ github.head_ref }}

      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
          reporter: github-pr-review
          filter_mode: file

  clj-kondo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.2
        with:
          ref: ${{ github.head_ref }}

      - name: Lint Clojure
        uses: nnichols/clojure-lint-action@98e94f7cfeaa84b19c93f2b960b7f9f3afa89758
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          filter_mode: file
