name: Linter
on: [pull_request]

jobs:
  spell-check:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.4
        with:
          ref: ${{ github.head_ref }}

      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
          reporter: github-pr-review
          filter_mode: file

  clj-kondo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.4
        with:
          ref: ${{ github.head_ref }}

      - name: Lint Clojure
        uses: nnichols/clojure-lint-action@12ec94d39067c0da987b5ac32a0edd1b565b0df8
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          filter_mode: file
